#define DEBUG

#define DISPLAY_CS_PIN 13
#define DISPLAY_CLK_PIN 12
#define DISPLAY_DATA_PIN 11

#define SENSOR_PIN 10


#define HUMIDIFICATION_RELAY_PIN 9
#define HEATING_RELAY_PIN 8
#define COOLING_RELAY_PIN 7

#define BUTTON_SELECT_PIN 4
#define BUTTON_PLUS_PIN 3
#define BUTTON_MINUS_PIN 2



//#define BUTTON_CONTROL_ON 2
